services:
  - type: web
    plan: free
    name: autofilterbot
    env: python
    buildCommand: pip3 install -r requirements.txt
    startCommand: python3 main.py
    repo: https://github.com/snowsbotz/Monkeyfilter.git   
    branch: main
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: APP_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: CHANNELS 
        sync: false
      - key: ADMINS
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_URL
        sync: false 
      - key: START_MESSAGE
        sync: false
      - key: FORCE_SUB_CHANNEL
        sync: false    
      - key: FORCE_SUB_MESSAGE
        sync: false
      - key: SHORT_API
        sync: false
      - key: SHORT_URL
        sync: false
      - key: PICS
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: AUTH_CHANNEL
        sync: false
      - key: WEBHOOK
        sync: false
    autoDeploy: false 
